---
title: "QC and smoothness"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read_data}
library(lmerTest)
library(reshape2)
library(ggplot2)

qc.fwhm <- read.csv("qc_multivolfwhm_cartesian.csv", header=TRUE)
qc.fwhm$X <- NULL
qc.fwhm$pipeline <- factor(qc.fwhm$pipeline, levels=c("Raw", "QSIPrep"))
smooth.compare <- dcast(qc.fwhm, scheme + subject ~ pipeline, value.var = "fwhm") 
smooth.compare$delta.fwhm <- with(smooth.compare, QSIPrep-Raw)
write.csv(smooth.compare, "nonspherical_multivolfwhm_comparisons.csv")
```


```{r plot_deltas}
ggplot(smooth.compare, aes(x=delta.fwhm, fill=scheme)) + geom_density() + facet_wrap(~scheme) + 
  theme_linedraw() + geom_vline(xintercept = 0) +
  scale_fill_brewer(palette="Paired", limits=levels(qc.fwhm$scheme)) 

```



```{r plot_smoothness}

ggplot(qc.fwhm, aes(x=scheme, y=fwhm, color=pipeline, fill=scheme)) + geom_boxplot() +
  theme_linedraw() + ggtitle("Output Smoothness") +
  ylab("Estimated FWHM (mm)") + xlab("Sampling Scheme") + 
  scale_fill_brewer(palette="Dark2") + scale_color_grey()

```


```{r q7_compare}
q7 <- subset(qc.fwhm, scheme=="DSI 789")
q7.fwhm.model <- lmer(fwhm ~ pipeline + (1 | subject), data=q7)
summary(q7.fwhm.model)
q7$fwhm.cen <- q7$fwhm - mean(q7$fwhm)

q7.model <- lm(qc ~ fwhm.cen, data=q7)
q7$qc <- q7.model$coefficients[1] + residuals(q7.model)
q7$fwhm <- NULL
ggplot(q7, aes(x=qc, fill=pipeline)) + geom_histogram()

q7.test <- lmer(qc ~ pipeline + (1 | subject), data=q7)
summary(q7.test)

q7.corrected <- dcast(q7, subject + scheme ~ pipeline, value.var = "qc")
ggplot(q7.corrected, aes(x=Raw, y=QSIPrep)) + 
  geom_abline() + geom_point() + ggtitle("q7 QC") + xlab("No Preprocessing")
```

```{r csdsi_compare}
csdsi <- subset(qc.fwhm, scheme=="CS-DSI")
csdsi.fwhm.model <- lmer(fwhm ~ pipeline + (1 | subject), data=csdsi)
summary(csdsi.fwhm.model)
csdsi$fwhm.cen <- csdsi$fwhm - mean(csdsi$fwhm)

csdsi.model <- lm(qc ~ fwhm.cen, data=csdsi)
csdsi$qc <- csdsi.model$coefficients[1] + residuals(csdsi.model)
csdsi$fwhm <- NULL
ggplot(csdsi, aes(x=qc, fill=pipeline)) + geom_histogram()

csdsi.test <- lmer(qc ~ pipeline + (1 | subject), csdsi)
summary(csdsi.test)

csdsi.corrected <- dcast(csdsi, subject + scheme ~ pipeline, value.var = "qc")
ggplot(csdsi.corrected, aes(x=Raw, y=QSIPrep)) + 
  geom_abline() + geom_point() + ggtitle("csdsi QC") + xlab("No Preprocessing")
```

```{r crash_compare}
crash <- subset(qc.fwhm, scheme=="DSI 258")
crash.fwhm.model <- lmer(fwhm ~ pipeline + (1 | subject), data=crash)
summary(crash.fwhm.model)
crash$fwhm.cen <- crash$fwhm - mean(crash$fwhm)

crash.model <- lm(qc ~ fwhm.cen, data=crash)
crash$qc <- crash.model$coefficients[1] + residuals(crash.model)
crash$fwhm <- NULL
ggplot(crash, aes(x=qc, fill=pipeline)) + geom_histogram()

crash.test <- lmer(qc ~ pipeline + (1 | subject), crash)
summary(crash.test)

crash.corrected <- dcast(crash, subject + scheme ~ pipeline, value.var = "qc")
ggplot(crash.corrected, aes(x=Raw, y=QSIPrep)) + 
  geom_abline() + geom_point() + ggtitle("crash QC") + xlab("No Preprocessing")
```

```{r corrected_qcs}

corrected.qcs <- rbind(q7.corrected, crash.corrected, csdsi.corrected)
write.csv(corrected.qcs, "nonspherical_fwhm-corrected_qcs.csv")

ggplot(corrected.qcs, aes(x=Raw, y=QSIPrep)) + geom_abline() +
  geom_point() + facet_wrap(~scheme) + theme_linedraw() + 
  scale_color_brewer(palette="Dark1", limits=levels(qc.fwhm$scheme))

```

```{r corrected_qcs2}

ggplot(corrected.qcs, aes(x=Raw, y=QSIPrep, color=scheme)) + geom_abline() +
  geom_point() + ggtitle("Non-Spherical Schemes") + xlab("Previous Pipeline") + 
  theme_linedraw() + 
  scale_color_brewer(palette="Paired", limits=levels(qc.fwhm$scheme))

```




```{r model_tables}
library(dplyr)
library(tidyr)
library(broom.mixed)

clean.table <- function(dtf, terms=c("pipelineQSIPrep", "fwhm.cen")){
  bonf <- p.adjust(dtf$p.value)
  bonf.txt <- sprintf("%.4e", bonf)
  dtf[["p-Value (Bonf.)"]] <- bonf.txt
  potential.cols <- c("Scheme", "Term", "Estimate", "Std. Error", "t-Statistic", "p-Value (Bonf.)")
  cols <- intersect(potential.cols, colnames(dtf))
  
  if ("Term" %in% colnames(dtf)){
    dtf <- subset(dtf, Term %in% terms)[,cols]
    dtf$Term <- sub("pipelineQSIPrep", "Pipeline", dtf$Term)
    dtf$Term <- sub("fwhm.cen", "FWHM", dtf$Term)
  }
return(dtf)
}

fwhm.models <- rbind(
  
  
  tidy(csdsi.fwhm.model) %>% mutate(scheme="CS-DSI"),
  tidy(crash.fwhm.model) %>% mutate(scheme="DSI 258"),
  tidy(q7.fwhm.model) %>% mutate(scheme="DSI 789")
) %>%
     mutate_each(funs(round(., 3)), -term, -scheme, -effect, -group, -p.value) %>%
    plyr::rename(c("scheme"="Scheme", "term"="Term", "estimate"="Estimate", "std.error"="Std. Error",
                 "statistic"="t-Statistic")) %>%
  clean.table() %>% select(-Term)


write.table(fwhm.models, file = "cart_fwhm_stats.txt", sep = ",", quote = FALSE, row.names = F)



qc.models <- rbind(
  tidy(csdsi.test) %>% mutate(scheme="CS-DSI"),
  tidy(crash.test) %>% mutate(scheme="DSI 258"),
  tidy(q7.test) %>% mutate(scheme="DSI 789")
) %>%
   mutate_each(funs(round(., 3)), -term, -scheme, -effect, -group, -p.value) %>%
  plyr::rename(c("scheme"="Scheme", "term"="Term", "estimate"="Estimate", "std.error"="Std. Error",
                 "statistic"="t-Statistic")) %>%
  clean.table() %>% select(-Term)

write.table(qc.models, file = "cart_qc_stats.txt", sep = ",", quote = FALSE, row.names = F)

```
